# Upload Assistant © 2025 Audionut & wastaken7 — Licensed under UAPL v1.0
import asyncio
import platform
from pathlib import Path
from typing import Any

import aiofiles
import httpx
from bs4 import BeautifulSoup

from src.domain_models.release import Meta
from src.integrations.media.language_adapter import languages_manager
from src.integrations.observability.runtime_support import logger
from src.integrations.trackers.cookie_auth import CookieAuthUploader, CookieValidator
from src.integrations.trackers.description_builder import DescriptionBuilder


class FunFile:
    """
    FF Private Torrent Tracker
    """

    auth_type = "cookies"
    tracker = "FUNFILE"
    display_name = "FunFile"
    banned_groups: tuple[str, ...] = ()
    source_flag = "FunFile"
    base_url = "https://www.funfile.org"
    auth_token = None
    torrent_url = f"{base_url}/details.php?id="
    requests_url = f"{base_url}/requests.php"
    supported_categories = ("TV", "MOVIE")
    tracker_urls = ("tracker.funfile.org",)
    allows_bloated_audio = True

    def __init__(self, config: dict[str, Any]) -> None:
        self.config = config
        self.cookie_validator = CookieValidator(config)
        self.cookie_auth_uploader = CookieAuthUploader(config)
        self.session = httpx.AsyncClient(headers={"User-Agent": f"Upload-Assistant/2.3 ({platform.system()} {platform.release()})"}, timeout=30.0)

    async def validate_credentials(self, meta: Meta) -> bool:
        from src.integrations.trackers.cookie_auth import find_cookie_file

        cookie_file = find_cookie_file(meta.base_dir, self.tracker, self.config)
        if not Path(cookie_file).exists():
            await self.login(meta)

        cookie_jar = await self.cookie_validator.load_session_cookies(meta, self.tracker)
        if cookie_jar is None:
            return False
        self.session.cookies = cookie_jar
        return True

    async def validate_cookies(self, meta: Meta) -> bool:
        return await self.cookie_validator.cookie_validation(
            meta=meta,
            tracker=self.tracker,
            test_url=f"{self.base_url}/upload.php",
            success_text="friends.php",
        )

    async def login(self, meta: Meta) -> None:
        from src.integrations.trackers.cookie_auth import find_cookie_file

        cookie_file = find_cookie_file(meta.base_dir, self.tracker, self.config)
        logger.info(f"{self.tracker}: Trying to login...", extra={"markup": False})
        response = await self.session.post("https://www.funfile.org/takelogin.php", data=self._login_payload())
        if response.status_code != 302:
            logger.info(f"{self.tracker}: Login failed. Status code: {response.status_code}", extra={"markup": False})
            return
        logger.info(f"{self.tracker}: Login Successful!", extra={"markup": False})
        await self._write_cookie_file(cookie_file)
        logger.info(f"{self.tracker}: Saving the cookie file...", extra={"markup": False})

    def _login_payload(self) -> dict[str, Any]:
        tracker_config = self.config["TRACKERS"][self.tracker]
        return {
            "returnto": "/index.php",
            "username": tracker_config["username"],
            "password": tracker_config["password"],
            "login": "Login",
        }

    async def _write_cookie_file(self, cookie_file: str | Path) -> None:
        async with aiofiles.open(cookie_file, "w") as handle:
            await handle.write("# Netscape HTTP Cookie File\n")
            await handle.write("# This file was generated by an automated script.\n\n")
            for cookie in self.session.cookies.jar:
                await handle.write(self._cookie_line(cookie))

    @staticmethod
    def _cookie_line(cookie: Any) -> str:
        domain = str(cookie.domain)
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        secure = "TRUE" if cookie.secure else "FALSE"
        expires = str(cookie.expires) if cookie.expires else "0"
        return f"{domain}\t{include_subdomains}\t{cookie.path}\t{secure}\t{expires}\t{cookie.name}\t{cookie.value}\n"

    async def search_existing(self, meta: Meta) -> list[str]:
        cookie_jar = await self.cookie_validator.load_session_cookies(meta, self.tracker)
        if cookie_jar is None:
            return []
        self.session.cookies = cookie_jar
        search_url = self._search_url(meta)
        response = await self.session.get(search_url)
        response = await self._authenticated_search_response(meta, search_url, response)
        if response is None:
            return []
        return self._nonempty_lines(response.text)

    @classmethod
    def _search_url(cls, meta: Meta) -> str:
        query = cls._search_query(meta)
        return f"{cls.base_url}/suggest.php?q={query}"

    @staticmethod
    def _search_query(meta: Meta) -> str:
        if meta.category == "TV":
            return f"{meta.title} {meta.season}{meta.episode}"
        return str(meta.title)

    async def _authenticated_search_response(self, meta: Meta, search_url: str, response: httpx.Response) -> httpx.Response | None:
        if not self._requires_login(response):
            response.raise_for_status()
            return response
        await self.login(meta)
        retry = await self.session.get(search_url)
        retry.raise_for_status()
        if not self._requires_login(retry):
            return retry
        await self.cookie_validator.handle_validation_failure(meta, self.tracker, retry.text)
        meta.skipping = self.tracker
        return None

    @staticmethod
    def _requires_login(response: httpx.Response) -> bool:
        return response.status_code != 200 or "login" in str(response.url).casefold() or "login" in response.text.casefold()

    @staticmethod
    def _nonempty_lines(value: str) -> list[str]:
        return [line.strip() for line in value.splitlines() if line.strip()]

    async def get_requests(self, meta: Meta) -> bool | list[dict[str, str]]:
        if not self._request_checks_enabled():
            return False
        try:
            return await self._fetch_requests(meta)
        except Exception as error:
            logger.info(f"{self.tracker}: An error occurred while fetching requests: {error}", extra={"markup": False})
            return []

    def _request_checks_enabled(self) -> bool:
        return bool(self.config["TRACKERS"][self.tracker].get("check_requests", False))

    async def _fetch_requests(self, meta: Meta) -> list[dict[str, str]]:
        cookie_jar = await self.cookie_validator.load_session_cookies(meta, self.tracker)
        if cookie_jar is None:
            return []
        self.session.cookies = cookie_jar
        response_text = await self._request_search_text(meta)
        results = self._parse_requests(response_text)
        self._log_requests(results)
        return results

    async def _request_search_text(self, meta: Meta) -> str:
        category = self.get_type_id(meta)
        queries = self._request_queries(meta.title)
        urls = [f"{self.requests_url}?filter=open&category={category}&search={query}" for query in queries]
        responses = await asyncio.gather(*(self.session.get(url) for url in urls))
        for response in responses:
            response.raise_for_status()
        return "".join(response.text for response in responses)

    @staticmethod
    def _request_queries(title: str) -> list[str]:
        dotted = title.replace(" ", ".")
        return [title] if dotted == title else [title, dotted]

    @classmethod
    def _parse_requests(cls, html: str) -> list[dict[str, str]]:
        soup = BeautifulSoup(html, "html.parser")
        return [result for row in soup.select("td.mf_content table tr") if (result := cls._request_row(row)) is not None]

    @staticmethod
    def _request_row(row: Any) -> dict[str, str] | None:
        name_element = row.select_one("td.row3 nobr a b")
        if not name_element:
            return None
        link_element = name_element.find_parent("a")
        all_tds = row.find_all("td", class_="row3")
        return {
            "Name": name_element.text.strip(),
            "Link": str(link_element["href"]) if link_element and link_element.has_attr("href") else "",
            "Reward": all_tds[2].text.strip() if len(all_tds) > 2 else "",
        }

    def _log_requests(self, results: list[dict[str, str]]) -> None:
        if not results:
            return
        lines = [f"\n{self.tracker}: [bold yellow]Your upload may fulfill the following request(s), check it out:[/bold yellow]\n"]
        for result in results:
            lines.extend(self._request_result_lines(result))
        logger.info("\n".join(lines))

    @staticmethod
    def _request_result_lines(result: dict[str, str]) -> list[str]:
        return [
            f"[bold green]Name:[/bold green] {result['Name']}",
            f"[bold green]Reward:[/bold green] {result['Reward']}",
            f"[bold green]Link:[/bold green] {result['Link']}",
            "",
        ]

    async def generate_description(self, meta: Meta) -> str:
        builder = DescriptionBuilder(self.tracker, self.config)
        return await builder.general_description_generator(
            meta,
            bluray=False,
            book=False,
            custom_signature=False,
            game=False,
            nfo=False,
            signature=f"[url=https://github.com/wastaken7/Upload-Assistant][center][size=1]{meta.ua_signature}[/size][/center][/url]",
        )

    def get_type_id(self, meta: Meta) -> str:
        if meta.anime:
            return "44"
        category = meta.category

        if category == "MOVIE":
            return "19"

        if category == "TV":
            return "7"

        return "19"

    def file_information(self, meta: Meta) -> None:
        vc = meta.video_codec
        if vc:
            self.video_codec = vc.strip().lower()

        ve = meta.video_encode
        if ve:
            self.video_encode = ve.strip().lower()

        vs = meta.source
        if vs:
            self.video_source = vs.strip().lower()

        vt = meta.type
        if vt:
            self.video_type = vt.strip().lower()

    def movie_type(self, _meta: Meta) -> str:
        # Possible values: "XviD", "DVDR", "x264", "x265", "MP4", "VCD"
        if self.video_source == "dvd":
            return "DVDR"

        if self.video_codec == "hevc":
            return "x265"
        return "x264"

    def tv_type(self, meta: Meta) -> str:
        if self.video_source == "dvd":
            return "DVDR"
        if self.video_source == "web":
            return self._sd_hd_label("Web", meta.sd)
        codec = "x265" if self.video_codec == "hevc" else "x264"
        return self._sd_hd_label(codec, meta.sd)

    @staticmethod
    def _sd_hd_label(prefix: str, sd: Any) -> str:
        return f"{prefix}-SD" if sd else f"{prefix}-HD"

    def anime_type(self, meta: Meta) -> str:
        # Possible values: "TVSeries", "TVSpecial", "Movie", "OVA", "ONA", "DVDSpecial"
        if meta.tvmaze_episode_data.get("season_number") == 0:
            return "TVSpecial"

        if self.video_source == "dvd":
            return "DVDSpecial"

        category = meta.category

        if category == "TV":
            return "TVSeries"

        if category == "MOVIE":
            return "Movie"

        return "TVSeries"

    def movie_source(self, _meta: Meta) -> str | None:
        # Possible values: "DVD", "DVDSCR", "Workprint", "TeleCine", "TeleSync", "CAM", "BluRay", "HD-DVD", "HDTV", "R5", "WebRIP"
        mapping = {
            "dvd": "DVD",
            "dvdscr": "DVDSCR",
            "workprint": "Workprint",
            "telecine": "TeleCine",
            "telesync": "TeleSync",
            "cam": "CAM",
            "bluray": "BluRay",
            "blu-ray": "BluRay",
            "hd-dvd": "HD-DVD",
            "hdtv": "HDTV",
            "r5": "R5",
            "web": "WebRIP",
            "webrip": "WebRIP",
        }

        src = (self.video_source or "").strip().lower()
        return mapping.get(src)

    def tv_source(self, _meta: Meta) -> str | None:
        # Possible values: "HDTV", "DSR", "PDTV", "TV", "DVD", "DvdScr", "BluRay", "WebRIP"
        mapping = {
            "hdtv": "HDTV",
            "dsr": "DSR",
            "pdtv": "PDTV",
            "tv": "TV",
            "dvd": "DVD",
            "dvdscr": "DvdScr",
            "bluray": "BluRay",
            "blu-ray": "BluRay",
            "web": "WebRIP",
            "webrip": "WebRIP",
        }

        src = (self.video_source or "").strip().lower()
        return mapping.get(src)

    def anime_source(self, _meta: Meta) -> str | None:
        # Possible values: "DVD", "BluRay", "Anime Series", "HDTV"
        mapping = {"hdtv": "HDTV", "tv": "HDTV", "dvd": "DVD", "bluray": "BluRay", "blu-ray": "BluRay", "web": "Anime Series", "webrip": "Anime Series"}

        src = (self.video_source or "").strip().lower()
        return mapping.get(src)

    def anime_v_dar(self, meta: Meta) -> str:
        if meta.is_disc == "BDMV":
            return "16_9"
        video_track = self._first_video_track(meta)
        return self._display_aspect_ratio(video_track)

    @classmethod
    def _first_video_track(cls, meta: Meta) -> dict[str, Any]:
        return next((track for track in cls._media_tracks(meta) if track.get("@type") == "Video"), {})

    @classmethod
    def _media_tracks(cls, meta: Meta) -> list[dict[str, Any]]:
        media = cls._media_mapping(meta)
        tracks = media.get("track", [])
        if not isinstance(tracks, list):
            return []
        return [track for track in tracks if isinstance(track, dict)]

    @staticmethod
    def _media_mapping(meta: Meta) -> dict[str, Any]:
        if not isinstance(meta.mediainfo, dict):
            return {}
        media = meta.mediainfo.get("media", {})
        return media if isinstance(media, dict) else {}

    @staticmethod
    def _display_aspect_ratio(track: dict[str, Any]) -> str:
        value = track.get("DisplayAspectRatio")
        if not value:
            return "16_9"
        try:
            return "16_9" if float(value) > 1.34 else "4_3"
        except ValueError, TypeError:
            return "16_9"

    def anime_v_codec(self, _meta: Meta) -> str:
        # Possible values: "x264", "h264", "XviD", "DivX", "WMV", "VC1"
        if self.video_codec == "vc-1":
            return "VC1"

        if self.video_encode == "h.264":
            return "h264"
        return "x264"

    async def get_name(self, meta: Meta) -> str:
        return (meta.scene_name if meta.scene_name else meta.basename_no_ext.replace(" ", ".")) if meta.scene else meta.clean_name.replace(" ", ".")

    async def languages(self, meta: Meta) -> dict[str, list[str]]:
        if not meta.language_checked:
            await languages_manager.process_desc_language(meta, tracker=self.tracker)
        audio = self._anime_audio_fields(meta)
        subtitles = self._anime_subtitle_fields(meta)
        return {
            "anime_a_codec": audio[0],
            "anime_a_ch": audio[1],
            "anime_a_lang": audio[2],
            "anime_s_format": subtitles[0],
            "anime_s_type": subtitles[1],
            "anime_s_lang": subtitles[2],
        }

    @classmethod
    def _anime_audio_fields(cls, meta: Meta) -> tuple[list[str], list[str], list[str]]:
        languages = cls._language_values(meta.audio_languages)
        if not languages:
            return [], [], []
        codec = cls._anime_audio_codec(meta.audio)
        channel = cls._anime_audio_channel(meta.channels)
        codes = [cls._language_code(language) for language in languages]
        return [codec] * len(codes), [channel] * len(codes), codes

    @classmethod
    def _anime_subtitle_fields(cls, meta: Meta) -> tuple[list[str], list[str], list[str]]:
        languages = cls._language_values(meta.subtitle_languages)
        if not languages:
            return [], [], []
        codes = [cls._language_code(language) for language in languages]
        return ["srt"] * len(codes), ["sub"] * len(codes), codes

    @staticmethod
    def _language_values(value: Any) -> list[str]:
        return [str(item) for item in value] if isinstance(value, list) else []

    @staticmethod
    def _language_code(language: str) -> str:
        mapping = {"english": "en", "japanese": "jp", "korean": "kr", "thai": "th", "chinese": "zh"}
        return mapping.get(language.casefold(), "1")

    @staticmethod
    def _anime_audio_codec(audio: str) -> str:
        audio_desc = str(audio or "").casefold()
        options = (
            ("dts-es", "dtses"),
            ("dtses", "dtses"),
            ("dolby digital", "ac3"),
            ("aac", "aac"),
            ("ac3", "ac3"),
            ("dd", "ac3"),
            ("ogg", "ogg"),
            ("mp3", "mp3"),
            ("dts", "dts"),
            ("flac", "flac"),
            ("pcm", "pcm"),
            ("wma", "wma"),
        )
        return next((value for key, value in options if key in audio_desc), "0")

    @staticmethod
    def _anime_audio_channel(channels: str) -> str:
        return {"2.0": "2", "5.1": "5_1", "7.1": "7_1"}.get(channels, "0")

    async def get_poster(self, meta: Meta) -> tuple[str, bytes, str] | None:
        poster_url = meta.artwork_url

        if poster_url:
            async with httpx.AsyncClient() as client:
                response = await client.get(poster_url)
                if response.status_code == 200:
                    poster_ext = Path(poster_url).suffix or ".jpg"
                    poster_filename = f"{meta.name}{poster_ext}"
                    return (poster_filename, response.content, "image/jpeg")

        return None

    def get_nfo(self, meta: Meta) -> dict[str, tuple[str, Any, str]]:
        nfo_dir = Path(meta.base_dir) / "tmp" / meta.uuid
        nfo_files = list(nfo_dir.glob("*.nfo"))

        if nfo_files:
            nfo_path = nfo_files[0]

            return {"nfo": (nfo_path.name, nfo_path.open("rb"), "application/octet-stream")}
        return {}

    async def get_data(self, meta: Meta) -> dict[str, Any]:
        languages = await self.languages(meta)
        self.file_information(meta)

        data: dict[str, Any] = {
            "MAX_FILE_SIZE": 10000000,
            "type": self.get_type_id(meta),
            "tags": "",
            "descr": await self.generate_description(meta),
        }

        if meta.anime:
            data.update(
                {
                    "anime_type": self.anime_type(meta),
                    "anime_source": self.anime_source(meta),
                    "anime_container": "mkv",
                    "anime_v_res": meta.resolution,
                    "anime_v_dar": self.anime_v_dar(meta),
                    "anime_v_codec": self.anime_v_codec(meta),
                    "anime_a_codec[]": ["0", *languages.get("anime_a_codec", [])],
                    "anime_a_ch[]": ["0", *languages.get("anime_a_ch", [])],
                    "anime_a_lang[]": ["0", *languages.get("anime_a_lang", [])],
                    "anime_s_format[]": ["0", *languages.get("anime_s_format", [])],
                    "anime_s_type[]": ["0", *languages.get("anime_s_type", [])],
                    "anime_s_lang[]": ["0", *languages.get("anime_s_lang", [])],
                }
            )

        else:
            if meta.category == "MOVIE":
                data.update(
                    {
                        "movie_type": self.movie_type(meta),
                        "movie_source": self.movie_source(meta),
                        "movie_imdb": str(meta.imdb_info.get("imdb_url", "")),
                        "pack": 0,
                    }
                )

            if meta.category == "TV":
                data.update(
                    {
                        "tv_type": self.tv_type(meta),
                        "tv_source": self.tv_source(meta),
                        "tv_imdb": str(meta.imdb_info.get("imdb_url", "")),
                        "pack": 1 if meta.tv_pack else 0,
                    }
                )

        return data

    async def upload(self, meta: Meta) -> bool:
        cookie_jar = await self.cookie_validator.load_session_cookies(meta, self.tracker)
        if cookie_jar is None:
            return False
        self.session.cookies = cookie_jar
        data = await self.get_data(meta)
        torrent_name = await self.get_name(meta)
        files: dict[str, Any] = {}
        poster = await self.get_poster(meta)
        if poster:
            files["poster"] = poster
        nfo = self.get_nfo(meta)
        if nfo:
            files["nfo"] = nfo["nfo"]

        return await self.cookie_auth_uploader.handle_upload(
            meta=meta,
            tracker=self.tracker,
            source_flag=self.source_flag,
            torrent_url=self.torrent_url,
            data=data,
            torrent_field_name="file",
            torrent_name=torrent_name,
            upload_cookies=self.session.cookies,
            upload_url=f"{self.base_url}/takeupload.php",
            id_pattern=r"details\.php\?id=(\d+)",
            success_status_code="302",
            additional_files=files,
        )
